trigger:
  - master
  - feature/*

resources:
  repositories:
    - repository: bp-via-checkmarx
      type: git
      name: Vulnerability_Identification_and_Awareness/bp-via-checkmarx
      ref: feature/test-github-repo

variables:
  - group: Web-Goat #delete 

stages:
- stage: SecurityScanStage
  displayName: Checkmarx Security Scan Stage
  jobs:

  - job: SecurityScanJob
    displayName: Checkmarx Security Scan Job

    pool:
      vmImage: ubuntu-latest

    steps:
    - template: /templates-common/cx_ado_template/cx-ado-template.yml@bp-via-checkmarx
      parameters:
        releaseBranches:
        - master
        - main
        - release
        repoNames:
        - $(Build.Repository.Name)
        repoIDS:
        - $(Build.Repository.ID)
        repoBranchNames:
        - master
        snowApplicationPackageNumber: SPKG0017565
        projectInformalName: WebGoat
        itServiceName: Code-Scanning
        itServiceNumber: ITSVC0010472
        scaServiceConnection: checkmarx-sca-CodeScanning
        sastServiceConnection: checkmarx-sast-CodeScanning
        isMicroService: no
        sast: true
        sca: false
        targetBranch: refs/heads/feature/define-default-branch
        gitHubScan: true

