trigger:
  - master
  - feature/*

resources:
  repositories:
    - repository: bp-via-checkmarx
      type: git
      name: Vulnerability_Identification_and_Awareness/bp-via-checkmarx
      #ref: feature/add-it-service-custom-field

variables:
  - group: Web-Goat #delete 

stages:
- stage: SecurityScanStage
  displayName: Checkmarx Security Scan Stage
  jobs:

  - job: SecurityScanJob
    displayName: Checkmarx Security Scan Job

    pool:
      vmImage: ubuntu-latest

    steps:
    - template: /templates-common/cx_ado_template/cx-ado-template.yml@bp-via-checkmarx
      parameters:
        releaseBranches:
        - master
        - main
        - release
        repoNames:
        - $(Build.Repository.Name)
        - checkmarx-health-monitor
        - checkmarx-queue-monitor
        repoIDS:
        - $(Build.Repository.ID)
        - b98e1487-8847-4a57-9ee3-f647cc0d3aa8
        - 834e1ba6-3be7-49f4-bd96-0b7194e0cc2c
        repoBranchNames:
        - master
        - master
        - master
        snowApplicationPackageNumber: SPKG0017565
        projectInformalName: WebGoat
        itServiceName: Code-Scanning
        itServiceNumber: ITSVC0010472
        scaServiceConnection: checkmarx-sca-CodeScanning
        sastServiceConnection: checkmarx-sast-CodeScanning
        isMicroService: no
        sast: true
        sca: false
        #countLOC: false
        targetBranch: refs/heads/feature/define-default-branch
        #gitHubScan: true 
        #forceScan: true
        #scanTimeout: 1 works
        #generatePDFReport: true
        #avoidDuplicateScans: true
        #fullScansScheduled: true
        #fullScanCycle: 2

